package Entity;
// Generated 8/03/2018 08:04:03 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name="provider")
public class Provider implements Serializable{
    @Id
    @GeneratedValue 
    private int id;
    @Column(name = "name")
    private String name;
    @Column(name = "phone_number")
    private String phoneNumber;
    @Column(name = "rut")
    private String rut;
    
    @OneToMany(mappedBy="provider")
    private Set<PurchaseOrder> purchaseOrders;

    public Provider() {
    }

	
    public Provider(int id, String name, String phoneNumber, String rut) {
        this.id = id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.rut = rut;
    }
    public Provider(int id, String name, String phoneNumber, String rut, Set purchaseOrders) {
       this.id = id;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.rut = rut;
       this.purchaseOrders = purchaseOrders;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Set getPurchaseOrders() {
        return this.purchaseOrders;
    }
    
    public void setPurchaseOrders(Set purchaseOrders) {
        this.purchaseOrders = purchaseOrders;
    }
    
    public void addPurchaseOrder(PurchaseOrder purchaseOrders) {
        this.purchaseOrders.add(purchaseOrders);
    }
}


