/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

/**
 *
 * @author Mis-Dark
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        buttonAeroRight1 = new org.edisoncor.gui.button.ButtonAeroRight();
        buttonAeroRight2 = new org.edisoncor.gui.button.ButtonAeroRight();
        buttonAeroRight3 = new org.edisoncor.gui.button.ButtonAeroRight();
        buttonAeroRight4 = new org.edisoncor.gui.button.ButtonAeroRight();
        buttonAeroRight6 = new org.edisoncor.gui.button.ButtonAeroRight();
        buttonAeroRight5 = new org.edisoncor.gui.button.ButtonAeroRight();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SURTIALISS");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        buttonAeroRight1.setText("Usuarios");
        jPanel1.add(buttonAeroRight1);

        buttonAeroRight2.setText("Clientes");
        jPanel1.add(buttonAeroRight2);

        buttonAeroRight3.setText("Productos");
        jPanel1.add(buttonAeroRight3);

        buttonAeroRight4.setText("Facturas");
        jPanel1.add(buttonAeroRight4);

        buttonAeroRight6.setText("Inventario");
        jPanel1.add(buttonAeroRight6);

        buttonAeroRight5.setText("Reportes");
        jPanel1.add(buttonAeroRight5);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 275, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight1;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight2;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight3;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight4;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight5;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
