/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Facturacion;

import Controladores.FacturaController;
import Controladores.ImprimirFactura;
import Controladores.ImprimirPDf;
import Entity.Facturas;
import Entity.Product;
import Modelos.FacturasBD;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Caja1
 */
public class FacturaView extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    FacturaController OperacionesFactura;
    DefaultTableModel ListaProducto;
    String[][] Clientes;
    String[] ClienteSelecionado;
    int dia;
    Product product;
    int points;
    //static int NumeroFacturaCreada = 0;

    public FacturaView() {
        initComponents();
        this.setTitle("Factura de Venta");
        OperacionesFactura = new FacturaController();
        Clientes = OperacionesFactura.getConsumerDocumentName();
        ClienteSelecionado = new String[2];
        OperacionesFactura.CargarClientes(this.clientes);
        this.txtTotal.setText("0");
        PrepararTabla();
        this.txtCodigo.requestFocus();
        this.initCombobox();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.points = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTranslucido1 = new org.edisoncor.gui.panel.PanelTranslucido();
        labelRect4 = new org.edisoncor.gui.label.LabelRect();
        clientes = new javax.swing.JComboBox();
        isCredit = new javax.swing.JRadioButton();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        panelTranslucido2 = new org.edisoncor.gui.panel.PanelTranslucido();
        labelRect5 = new org.edisoncor.gui.label.LabelRect();
        labelRect6 = new org.edisoncor.gui.label.LabelRect();
        txtCantidad = new org.edisoncor.gui.textField.TextField();
        labelRect7 = new org.edisoncor.gui.label.LabelRect();
        txtCodigo = new org.edisoncor.gui.textField.TextField();
        txtPrecio = new org.edisoncor.gui.textField.TextField();
        labelRect8 = new org.edisoncor.gui.label.LabelRect();
        btnSumar = new org.edisoncor.gui.button.ButtonIcon();
        jcbName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelTranslucido3 = new org.edisoncor.gui.panel.PanelTranslucido();
        txtCambio = new org.edisoncor.gui.textField.TextField();
        labelRect9 = new org.edisoncor.gui.label.LabelRect();
        labelRect10 = new org.edisoncor.gui.label.LabelRect();
        txtEfectivo = new org.edisoncor.gui.textField.TextField();
        labelRect11 = new org.edisoncor.gui.label.LabelRect();
        txtTotal = new org.edisoncor.gui.textField.TextField();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();
        panelTranslucido4 = new org.edisoncor.gui.panel.PanelTranslucido();
        buttonAero1 = new org.edisoncor.gui.button.ButtonAero();
        buttonAero2 = new org.edisoncor.gui.button.ButtonAero();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        labelRect4.setText("Cliente:");
        labelRect4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        clientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clientesItemStateChanged(evt);
            }
        });
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        isCredit.setForeground(new java.awt.Color(245, 243, 243));
        isCredit.setText("¿Fiado?");
        isCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isCreditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucido1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelRect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(isCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isCredit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelHeader1.setText("Factura de venta");
        labelHeader1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        labelRect5.setText("Nombre:");
        labelRect5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labelRect6.setText("Cantidad:");
        labelRect6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labelRect7.setText("Codigo:");
        labelRect7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        txtCodigo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtPrecio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labelRect8.setText("Precio:");
        labelRect8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/suma.png"))); // NOI18N
        btnSumar.setText("Agregar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        jcbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 251, 251));
        jLabel1.setText("Producto:");

        txtName.setEditable(false);

        javax.swing.GroupLayout panelTranslucido2Layout = new javax.swing.GroupLayout(panelTranslucido2);
        panelTranslucido2.setLayout(panelTranslucido2Layout);
        panelTranslucido2Layout.setHorizontalGroup(
            panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRect5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRect7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jcbName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRect6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRect8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panelTranslucido2Layout.setVerticalGroup(
            panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido2Layout.createSequentialGroup()
                .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucido2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRect7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRect6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRect5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRect8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTranslucido2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtCambio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        labelRect9.setText("Cambio");
        labelRect9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        labelRect10.setText("Efectivo");
        labelRect10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        txtEfectivo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });

        labelRect11.setText("Total");
        labelRect11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        txtTotal.setEnabled(false);
        txtTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelTranslucido3Layout = new javax.swing.GroupLayout(panelTranslucido3);
        panelTranslucido3.setLayout(panelTranslucido3Layout);
        panelTranslucido3Layout.setHorizontalGroup(
            panelTranslucido3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelRect11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelRect10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRect9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        panelTranslucido3Layout.setVerticalGroup(
            panelTranslucido3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTranslucido3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRect11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRect10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRect9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/menos.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");
        buttonIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIcon1ActionPerformed(evt);
            }
        });

        buttonAero1.setText("Cancelar");
        buttonAero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero1ActionPerformed(evt);
            }
        });

        buttonAero2.setText("Imprimir");
        buttonAero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucido4Layout = new javax.swing.GroupLayout(panelTranslucido4);
        panelTranslucido4.setLayout(panelTranslucido4Layout);
        panelTranslucido4Layout.setHorizontalGroup(
            panelTranslucido4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido4Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(buttonAero2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        panelTranslucido4Layout.setVerticalGroup(
            panelTranslucido4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAero2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ADD, 0));
        jMenuItem1.setText("Sumar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PLUS, 0));
        jMenuItem2.setText("Sumar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SUBTRACT, 0));
        jMenuItem3.setText("Restar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, 0));
        jMenuItem4.setText("Restar2");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
        jMenuItem5.setText("NuevoCodigo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_UP, 0));
        jMenuItem6.setText("IngresarEfectivo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_DOWN, 0));
        jMenuItem7.setText("Registrar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Imprimir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Cancelar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem10.setText("NuevaFactura");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTranslucido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelTranslucido3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTranslucido4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTranslucido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelTranslucido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTranslucido4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttonAero1ActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        this.txtCodigo.requestFocus();
    }//GEN-LAST:event_clientesActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        CargarCampos();
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void clientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clientesItemStateChanged
        for (int i = 0; i < Clientes.length; i++) {
            if (Clientes[i][1].equalsIgnoreCase(evt.getItem().toString())) {
                ClienteSelecionado[0] = this.Clientes[i][0];
                ClienteSelecionado[1] = this.Clientes[i][1];
                this.txtCodigo.requestFocus();
                if(this.OperacionesFactura.CreditoCliente(this.ClienteSelecionado[0]) == "SI"){
                    this.isCredit.enable();
                }else{
                    this.isCredit.disable();
                }
            }
        }
    }//GEN-LAST:event_clientesItemStateChanged

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        this.ComprobarExistencia();
    }//GEN-LAST:event_btnSumarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.ComprobarExistencia();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.ComprobarExistencia();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void buttonIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIcon1ActionPerformed
        this.quitar();
    }//GEN-LAST:event_buttonIcon1ActionPerformed

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
        CalcularCambio();
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void buttonAero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero2ActionPerformed
        Facturas invoice = this.GuardarBD();
        this.Imprimir(invoice);
        this.finishSale();
    }//GEN-LAST:event_buttonAero2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.quitar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.quitar();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.txtCodigo.requestFocusInWindow();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.txtEfectivo.requestFocusInWindow();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        GuardarBD();
        this.finishSale();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Facturas invoice = GuardarBD();
        Imprimir(invoice);
        this.finishSale();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FacturaView fac = new FacturaView();
        fac.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void isCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isCreditActionPerformed

    private void jcbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNameActionPerformed
        if("comboBoxEdited".equals(evt.getActionCommand())){
            Product product = (Product) this.jcbName.getSelectedItem();
            this.txtCodigo.setText(product.getBarCode());
            this.CargarCampos();
        }
    }//GEN-LAST:event_jcbNameActionPerformed

    private void PrepararTabla() {
        ListaProducto = new DefaultTableModel();
        String[] columnas = {"ID", "Producto", "Cantidad", "Valor unidad", "Valor total","Puntos"};
        ListaProducto.addColumn(columnas[0]);
        ListaProducto.addColumn(columnas[1]);
        ListaProducto.addColumn(columnas[2]);
        ListaProducto.addColumn(columnas[3]);
        ListaProducto.addColumn(columnas[4]);
        ListaProducto.addColumn(columnas[5]);
        this.jTable1.setModel(ListaProducto);
    }

    private void CargarCampos() {
        try {
            this.product = OperacionesFactura.BuscarProducto(this.txtCodigo.getText());
            this.txtName.setText(product.getName());
            this.txtPrecio.setText(product.getSalePrice()+"");
            this.txtCantidad.setText("1");
            long codigo = Long.parseLong(this.txtCodigo.getText().trim());
            if (codigo < 1000) {
                this.txtPrecio.requestFocus();
            } else {
                this.ComprobarExistencia();
            }
        } catch (NumberFormatException ex) {
            this.ComprobarExistencia();
        } catch (NullPointerException ex) {
            this.txtCodigo.setText(null);
        }
    }

    private void Sumar() {
        int cantidad = 0;
        int precio = 0;
        try {
            cantidad = Integer.parseInt(this.txtCantidad.getText());
            precio = Integer.parseInt(this.txtPrecio.getText());
        } catch (NullPointerException ex) {
            cantidad = 1;
        }

        int total = cantidad * precio;
        long totalcuenta = Long.parseLong(this.txtTotal.getText());
        String[] filaFactura = new String[6];
        
        filaFactura[0] = this.txtCodigo.getText();
        filaFactura[1] = this.product.getName();
        filaFactura[2] = cantidad + "";
        
        if(this.product.getIsPayPoints()){
            if(!this.checkPointsCustomer(total)){
                JOptionPane.showMessageDialog(this, "No se puede agregar el premio, no tienes suficientes puntos.");
                this.rebootForm();
                return ;
            }
            filaFactura[3] = "0";
            filaFactura[4] = "0";
            filaFactura[5] = total+"";
            this.points -= total;
        }else{
            filaFactura[3] = precio+"";
            filaFactura[4] = total+"";
            filaFactura[5] = "0";
            totalcuenta += total;
        }
        
        this.txtTotal.setText("" + totalcuenta);
        this.ListaProducto.addRow(filaFactura);
        this.rebootForm();
    }

    private void rebootForm(){
        this.txtCantidad.setText("1");
        this.txtCodigo.setText(null);
        this.txtPrecio.setText("");
        this.txtName.setText("");
        this.txtCodigo.requestFocus();
    }
    private void ComprobarExistencia() {
        int a;
        Boolean Nosumado = true;
        try {
            a = Integer.parseInt(this.txtCodigo.getText());
        } catch (Exception e) {
            a = 2000;
        }
        if (a <= 1000) {
            Sumar();
        } else {
            for (int i = 0; i < this.ListaProducto.getRowCount(); i++) {
                if (this.txtCodigo.getText().equals(this.ListaProducto.getValueAt(i, 0).toString())) {
                    Nosumado = false;
                    Long total = Long.parseLong(this.txtTotal.getText()) - Long.parseLong(this.ListaProducto.getValueAt(i, 4).toString());
                    int cantidad = Integer.parseInt(this.ListaProducto.getValueAt(i, 2).toString()) + Integer.parseInt(this.txtCantidad.getText());
                    int precio = cantidad * Integer.parseInt(this.txtPrecio.getText());
                    this.ListaProducto.setValueAt(cantidad, i, 2);
                    this.ListaProducto.setValueAt(precio, i, 4);
                    total += precio;
                    this.txtTotal.setText(total + "");
                    this.txtCodigo.setText(null);
                    this.txtPrecio.setText("");
                    this.txtPrecio.setText("");
                    this.txtCodigo.requestFocus();
                }
            }
            if (Nosumado) {
                Sumar();
            }
        }
        this.jScrollPane1.getVerticalScrollBar().setValue(this.jScrollPane1.getVerticalScrollBar().getMaximum());
    }

    private void QuitarFila() {
        long total = Long.parseLong(this.txtTotal.getText());
        int FilaSelecionada = this.jTable1.getSelectedRow();
        int ValorRestar = Integer.parseInt(ListaProducto.getValueAt(FilaSelecionada, 4).toString());
        int CantidadActual = Integer.parseInt(ListaProducto.getValueAt(FilaSelecionada, 2).toString());
        int ValorUnidad = Integer.parseInt(ListaProducto.getValueAt(FilaSelecionada, 3).toString());
        if (CantidadActual != 1) {
            ListaProducto.setValueAt(CantidadActual - 1, FilaSelecionada, 2);
            int TotalNuevo = (CantidadActual - 1) * ValorUnidad;
            ListaProducto.setValueAt(TotalNuevo, FilaSelecionada, 4);
        } else {
            ListaProducto.removeRow(FilaSelecionada);
        }
        total -= ValorUnidad;
        this.txtTotal.setText("" + total);
    }

    private void quitar() {
        QuitarFila();
        long total = Long.parseLong(this.txtTotal.getText());
        for (int i = 0; i < ListaProducto.getRowCount(); i++) {
            int cant = 0;
            if ((this.txtCodigo.getText().equalsIgnoreCase(ListaProducto.getValueAt(i, 0).toString()))
                    && (this.txtPrecio.getText().equals(ListaProducto.getValueAt(i, 3).toString()))) {
                total -= Integer.parseInt(ListaProducto.getValueAt(i, 4).toString());
                this.points += Integer.parseInt(ListaProducto.getValueAt(i, 5).toString());
                if (this.txtCantidad.getText().equalsIgnoreCase(ListaProducto.getValueAt(i, 2).toString())) {
                    ListaProducto.removeRow(i);
                } else {
                    cant = (Integer.parseInt(ListaProducto.getValueAt(i, 2).toString())) - Integer.parseInt(this.txtCantidad.getText());
                    ListaProducto.setValueAt(cant, i, 2);
                    long subtotal = cant * (Integer.parseInt(ListaProducto.getValueAt(i, 4).toString()));
                    ListaProducto.setValueAt(subtotal, i, 4);
                    total += (Integer.parseInt(ListaProducto.getValueAt(i, 4).toString()));
                    this.points -= Integer.parseInt(ListaProducto.getValueAt(i, 5).toString());
                }
                this.txtTotal.setText("" + total);
                break;
            }
        }
    }

    private void Imprimir(Facturas invoice) {
        
        String[] datos = new String[]{
            invoice.getNumeroFactura()+"",
            invoice.getDateText(),
            invoice.getHourText(),
            this.ClienteSelecionado[0],
            this.ClienteSelecionado[1],
            this.txtTotal.getText(),
            this.txtEfectivo.getText(),
            this.txtCambio.getText()
        };
        ImprimirPDf pdf = new ImprimirPDf(ListaProducto, datos);
        ImprimirFactura imprimir = new ImprimirFactura(ListaProducto, datos);
        pdf.start();
        imprimir.start();
    }
 
    private int saveInvoice(){
        CalcularCambio();
        String isCredit = "No";
        if(this.isCredit.isSelected()){
            isCredit = "Si";
        }
        
        String[] DatosFactura = new String[]{
            this.ClienteSelecionado[0],
            this.txtTotal.getText(),
            isCredit,
            this.points+""
        };
        int num_invoice = this.OperacionesFactura.newInvoice(DatosFactura);
        return num_invoice;
    }
    
    private void saveDetails(int num_invoice){
        this.OperacionesFactura.saveDetailsInvoice(ListaProducto, num_invoice);
    }
    
    private Facturas GuardarBD() {
        ImprimirFactura imprimir = new ImprimirFactura();
        imprimir.openCash(); 
        
        int num_invoice = this.saveInvoice();
        this.saveDetails(num_invoice);
        FacturasBD invoice = new FacturasBD();
        Facturas invoice_data = invoice.findInvoice(""+num_invoice);
        return invoice_data;
    }
    
    private void finishSale(){
        this.setVisible(false);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Total: " + this.txtTotal.getText() + "\n" + "Efectivo " + this.txtEfectivo.getText() + "\n"
                + "Cambio " + this.txtCambio.getText());
    }

    private void CalcularCambio() {
        long total = Long.parseLong(this.txtTotal.getText());
        long efectivo;
        try {
            efectivo = Long.parseLong(this.txtEfectivo.getText());
        } catch (NumberFormatException ex) {
            efectivo = total;
            this.txtEfectivo.setText(total+"");
        }
        this.txtCambio.setText("" + (efectivo - total));
    }
    
    private void initCombobox(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Product productItem : this.OperacionesFactura.getAllProducts()){
            model.addElement(productItem);
        }
        this.jcbName.setModel(model);
        AutoCompleteDecorator.decorate(this.jcbName);
    }
    
    private boolean checkPointsCustomer(int poinsNew){
        long totalPoins = this.OperacionesFactura.getPointsCliente(this.ClienteSelecionado[0]);
        
        if((this.points + poinsNew) > totalPoins){
            return false;
        }else{
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon btnSumar;
    private org.edisoncor.gui.button.ButtonAero buttonAero1;
    private org.edisoncor.gui.button.ButtonAero buttonAero2;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private javax.swing.JComboBox clientes;
    private javax.swing.JRadioButton isCredit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbName;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelRect labelRect10;
    private org.edisoncor.gui.label.LabelRect labelRect11;
    private org.edisoncor.gui.label.LabelRect labelRect4;
    private org.edisoncor.gui.label.LabelRect labelRect5;
    private org.edisoncor.gui.label.LabelRect labelRect6;
    private org.edisoncor.gui.label.LabelRect labelRect7;
    private org.edisoncor.gui.label.LabelRect labelRect8;
    private org.edisoncor.gui.label.LabelRect labelRect9;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido1;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido2;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido3;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido4;
    private org.edisoncor.gui.textField.TextField txtCambio;
    private org.edisoncor.gui.textField.TextField txtCantidad;
    private org.edisoncor.gui.textField.TextField txtCodigo;
    private org.edisoncor.gui.textField.TextField txtEfectivo;
    private javax.swing.JTextField txtName;
    private org.edisoncor.gui.textField.TextField txtPrecio;
    private org.edisoncor.gui.textField.TextField txtTotal;
    // End of variables declaration//GEN-END:variables

}